name: CI/CD

on:
  push:
    branches: 
      - main
  workflow_dispatch:

jobs:
  atualiza-imagem-processo:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Configurar Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login Docker Hub com Variaveis
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build e Push Docker Hub
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/hello-app:sha-${{ github.sha }}

      - name: Configurar SSH
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Checkout do reposit√≥rio de manifests
        uses: actions/checkout@v4
        with:
          repository: VitoriaAmelia/hello-manifest
          ssh-key: ${{ secrets.SSH_PRIVATE_KEY }}
          path: manifests

      - name: Atualiza imagem
        run: |
          cd manifests/hello-app
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git checkout main
          sed -i "s#image: .*#image: ${{ secrets.DOCKER_USERNAME }}/hello-app:sha-${{ github.sha }}#g" deployment.yaml
          git add deployment.yaml
          if ! git diff --cached --quiet; then
            git commit -m "ci: update image to sha-${{ github.sha }}"
            git push origin main
          fi
